// <auto-generated />
using System;
using BaseCore.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseCore.Repository.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseCore.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BaseCore.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketListingId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TicketListingId");

                    b.HasIndex("CartId", "TicketListingId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BaseCore.Entities.ETicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrCodePayload")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TicketOrderId")
                        .HasColumnType("int");

                    b.Property<int>("TicketOrderItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("TicketOrderId");

                    b.HasIndex("TicketOrderItemId");

                    b.HasIndex("UserId");

                    b.ToTable("ETickets");
                });

            modelBuilder.Entity("BaseCore.Entities.FootballMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KickoffTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StadiumId");

                    b.ToTable("Matches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            Competition = "Premier League",
                            HomeTeamId = 1,
                            IsFeatured = true,
                            KickoffTime = new DateTime(2026, 5, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Slug = "man-utd-liverpool",
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            Competition = "Premier League",
                            HomeTeamId = 3,
                            IsFeatured = true,
                            KickoffTime = new DateTime(2026, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "arsenal-chelsea",
                            StadiumId = 2,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            Competition = "Premier League",
                            HomeTeamId = 5,
                            IsFeatured = true,
                            KickoffTime = new DateTime(2026, 5, 17, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Slug = "man-city-tottenham",
                            StadiumId = 3,
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-newcastle-brighton.webp",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "newcastle-vs-brighton-team-news-live",
                            Summary = "Live updates and team news as Newcastle prepare to face Brighton in a key Premier League match.",
                            Title = "Newcastle vs Brighton team news LIVE!"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-brentford-west-ham.webp",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "brentford-vs-west-ham-team-news-live",
                            Summary = "Follow the latest lineup updates before Brentford meet West Ham in London.",
                            Title = "Brentford vs West Ham team news LIVE!"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-arsenal-fatigue.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "arsenal-warrior-spirit-fatigue",
                            Summary = "Arsenal look for resilience and rotation as a demanding run tests their squad depth.",
                            Title = "Arsenal summoning warrior spirit in fight against fatigue"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-carrick-liverpool.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "carrick-man-utd-liverpool-favourites",
                            Summary = "The former midfielder reflects on the intensity, history and emotion of the fixture.",
                            Title = "Carrick: Man Utd games vs Liverpool some of my favourites"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-fernandes-radar.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "fernandes-chasing-de-bruyne-henry-record",
                            Summary = "Bruno Fernandes continues to climb the Premier League creative charts with another standout season.",
                            Title = "Fernandes chasing down De Bruyne and Henry record"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-neville-slot-carrick.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "neville-man-utd-liverpool-carrick-slot",
                            Summary = "The rivalry returns with major pressure on both dugouts as the season reaches a decisive stage.",
                            Title = "Neville: Man Utd vs Liverpool huge for Carrick and Slot"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-2-2-368x287.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "leeds-burnley-nine-point-gap",
                            Summary = "Leeds strengthen their survival hopes with a commanding result against a direct rival.",
                            Title = "Leeds as good as safe? Thumping Burnley win opens nine-point gap to drop"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-mount-man-utd.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "mount-man-utd-title-challengers",
                            Summary = "The midfielder believes United can take another step forward with a stronger campaign.",
                            Title = "Mount expects Man Utd to be title challengers next season"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-de-zerbi-spurs.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "de-zerbi-spurs-negativity",
                            Summary = "De Zerbi calls for focus and belief as Spurs try to change the mood around their season.",
                            Title = "'We're not relegated yet' - De Zerbi wants to end Spurs negativity"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Premier League",
                            ImageUrl = "/template-football/images/news-chelsea-forest-watch.jpg",
                            IsFeatured = true,
                            PublishedAt = new DateTime(2026, 5, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Season = "2025-2026",
                            Slug = "chelsea-nottingham-forest-how-to-watch",
                            Summary = "Chelsea and Nottingham Forest meet in a key Premier League fixture on Monday afternoon.",
                            Title = "How to watch Chelsea vs Nott'm Forest at 3pm on Monday"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TicketOrderId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.HasIndex("TicketOrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BaseCore.Entities.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 74310,
                            City = "Manchester",
                            Country = "England",
                            ImageUrl = "/template-football/images/alessio-festa-_ElVbiXREBM-unsplash.jpg",
                            Name = "Old Trafford"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60704,
                            City = "London",
                            Country = "England",
                            ImageUrl = "/template-football/images/william-hadley-JytQXLPXpNM-unsplash.jpg",
                            Name = "Emirates Stadium"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 53400,
                            City = "Manchester",
                            Country = "England",
                            ImageUrl = "/template-football/images/james-kirkup-LbT_j62t94U-unsplash.jpg",
                            Name = "Etihad Stadium"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.StadiumSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("MapHeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MapWidth")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MapX")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MapY")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId", "Code")
                        .IsUnique();

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 590m,
                            Capacity = 120,
                            Code = "E335",
                            MapHeight = 8m,
                            MapWidth = 8m,
                            MapX = 91m,
                            MapY = 44m,
                            Name = "East Stand E335",
                            StadiumId = 1,
                            Tier = "standard"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 632m,
                            Capacity = 90,
                            Code = "E132",
                            MapHeight = 8m,
                            MapWidth = 8m,
                            MapX = 82m,
                            MapY = 86m,
                            Name = "Away Section E132",
                            StadiumId = 1,
                            Tier = "away"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 1050m,
                            Capacity = 100,
                            Code = "N1405",
                            MapHeight = 10m,
                            MapWidth = 7m,
                            MapX = 83m,
                            MapY = 32m,
                            Name = "North Stand N1405",
                            StadiumId = 1,
                            Tier = "best"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 3795m,
                            Capacity = 48,
                            Code = "N3406",
                            MapHeight = 10m,
                            MapWidth = 7m,
                            MapX = 45m,
                            MapY = 12m,
                            Name = "VIP Hospitality N3406",
                            StadiumId = 1,
                            Tier = "vip"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 8000m,
                            Capacity = 24,
                            Code = "S221",
                            MapHeight = 6m,
                            MapWidth = 7m,
                            MapX = 42m,
                            MapY = 94m,
                            Name = "South VIP Box S221",
                            StadiumId = 1,
                            Tier = "vip"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clubs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Manchester",
                            Country = "England",
                            IsActive = true,
                            LogoUrl = "/template-football/images/epl-teams/ImageLoGo/Manchester-United-FC-logo.png",
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 2,
                            City = "Liverpool",
                            Country = "England",
                            IsActive = true,
                            LogoUrl = "/template-football/images/epl-teams/ImageLoGo/Liverpool-FC-logo.png",
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            Country = "England",
                            IsActive = true,
                            LogoUrl = "/template-football/images/epl-teams/ImageLoGo/Arsenal-FC-logo.png",
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = 4,
                            City = "London",
                            Country = "England",
                            IsActive = true,
                            LogoUrl = "/template-football/images/epl-teams/ImageLoGo/Chelsea-FC-logo.png",
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 5,
                            City = "Manchester",
                            Country = "England",
                            IsActive = true,
                            LogoUrl = "/template-football/images/epl-teams/ImageLoGo/Manchester-City-FC-logo.png",
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 6,
                            City = "London",
                            Country = "England",
                            IsActive = true,
                            LogoUrl = "/template-football/images/epl-teams/ImageLoGo/Tottenham-Hotspur-logo.png",
                            Name = "Tottenham Hotspur"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.TicketCheckin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CheckinCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ETicketId")
                        .HasColumnType("int");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("CheckinCode")
                        .IsUnique();

                    b.HasIndex("ETicketId");

                    b.ToTable("TicketCheckins");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("StadiumSectionId")
                        .HasColumnType("int");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("StadiumSectionId");

                    b.ToTable("Tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 36,
                            DeliveryMethod = "Mobile Tickets",
                            IsVerified = true,
                            MatchId = 1,
                            RowLabel = "Row 7",
                            SellerName = "Club Ticket Office",
                            StadiumSectionId = 1,
                            TicketType = "standard",
                            Title = "E335",
                            UnitPrice = 590m
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 24,
                            DeliveryMethod = "Mobile Tickets",
                            IsVerified = true,
                            MatchId = 1,
                            RowLabel = "Block E132",
                            SellerName = "Club Ticket Office",
                            StadiumSectionId = 2,
                            TicketType = "away",
                            Title = "Away Section",
                            UnitPrice = 632m
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 28,
                            DeliveryMethod = "Mobile Tickets",
                            IsVerified = true,
                            MatchId = 1,
                            RowLabel = "Lower Tier",
                            SellerName = "Seat Market",
                            StadiumSectionId = 3,
                            TicketType = "best",
                            Title = "N1405",
                            UnitPrice = 1050m
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 12,
                            DeliveryMethod = "Mobile Tickets",
                            IsVerified = true,
                            MatchId = 1,
                            RowLabel = "Hospitality",
                            SellerName = "Club Partner",
                            StadiumSectionId = 4,
                            TicketType = "vip",
                            Title = "N3406 VIP",
                            UnitPrice = 3795m
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 8,
                            DeliveryMethod = "Mobile Tickets",
                            IsVerified = true,
                            MatchId = 1,
                            RowLabel = "Director Seats",
                            SellerName = "Hospitality Direct",
                            StadiumSectionId = 5,
                            TicketType = "vip",
                            Title = "S221 VIP Box",
                            UnitPrice = 8000m
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.TicketOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("BaseCore.Entities.TicketOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketListingId")
                        .HasColumnType("int");

                    b.Property<int>("TicketOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TicketListingId");

                    b.HasIndex("TicketOrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("BaseCore.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Contact = "",
                            Created = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@robotvibot.com",
                            Image = "",
                            IsActive = true,
                            Name = "Administrator",
                            Password = "admin123",
                            Phone = "0123456789",
                            Position = "System Administrator",
                            Salt = new byte[0],
                            UserName = "admin",
                            UserType = 1
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Contact = "",
                            Created = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@basecore.local",
                            Image = "",
                            IsActive = true,
                            Name = "Default User",
                            Password = "user123",
                            Phone = "0987654321",
                            Position = "Customer",
                            Salt = new byte[0],
                            UserName = "user",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.Cart", b =>
                {
                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.CartItem", b =>
                {
                    b.HasOne("BaseCore.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.TicketListing", "TicketListing")
                        .WithMany("CartItems")
                        .HasForeignKey("TicketListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("TicketListing");
                });

            modelBuilder.Entity("BaseCore.Entities.ETicket", b =>
                {
                    b.HasOne("BaseCore.Entities.TicketOrder", "TicketOrder")
                        .WithMany("ETickets")
                        .HasForeignKey("TicketOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.TicketOrderItem", "TicketOrderItem")
                        .WithMany("ETickets")
                        .HasForeignKey("TicketOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TicketOrder");

                    b.Navigation("TicketOrderItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.FootballMatch", b =>
                {
                    b.HasOne("BaseCore.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("BaseCore.Entities.Payment", b =>
                {
                    b.HasOne("BaseCore.Entities.TicketOrder", "TicketOrder")
                        .WithMany("Payments")
                        .HasForeignKey("TicketOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketOrder");
                });

            modelBuilder.Entity("BaseCore.Entities.StadiumSection", b =>
                {
                    b.HasOne("BaseCore.Entities.Stadium", "Stadium")
                        .WithMany("Sections")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketCheckin", b =>
                {
                    b.HasOne("BaseCore.Entities.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.ETicket", "ETicket")
                        .WithMany("Checkins")
                        .HasForeignKey("ETicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedByUser");

                    b.Navigation("ETicket");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketListing", b =>
                {
                    b.HasOne("BaseCore.Entities.FootballMatch", "Match")
                        .WithMany("TicketListings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.StadiumSection", "StadiumSection")
                        .WithMany("TicketListings")
                        .HasForeignKey("StadiumSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("StadiumSection");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketOrder", b =>
                {
                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketOrderItem", b =>
                {
                    b.HasOne("BaseCore.Entities.TicketListing", "TicketListing")
                        .WithMany("TicketOrderItems")
                        .HasForeignKey("TicketListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.TicketOrder", "TicketOrder")
                        .WithMany("Items")
                        .HasForeignKey("TicketOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketListing");

                    b.Navigation("TicketOrder");
                });

            modelBuilder.Entity("BaseCore.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BaseCore.Entities.ETicket", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("BaseCore.Entities.FootballMatch", b =>
                {
                    b.Navigation("TicketListings");
                });

            modelBuilder.Entity("BaseCore.Entities.Stadium", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("BaseCore.Entities.StadiumSection", b =>
                {
                    b.Navigation("TicketListings");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketListing", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("TicketOrderItems");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketOrder", b =>
                {
                    b.Navigation("ETickets");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BaseCore.Entities.TicketOrderItem", b =>
                {
                    b.Navigation("ETickets");
                });
#pragma warning restore 612, 618
        }
    }
}
